name: Build & upload APK to TestApp.io

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop

jobs:
  unit_test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@5.0.0

      - name: Run Unit Tests
        run: ./gradlew test

  build:
    name: Build and upload to TestApp.io
    needs: unit_test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Ecrire un step, qui à partir du context, determine le type de build
      # Utiliser les context pour determiner la branche github.ref_type

      - name: Determine build type
        id: build_type
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
              echo "BUILD_TYPE=Release" >> $GITHUB_OUTPUT
          else
              echo "BUILD_TYPE=Debug" >> $GITHUB_OUTPUT
          fi

      # echo "MA_VAR=Debug" >> $GITHUB_OUTPUT
      # echo "MA_VAR=Release" >> $GITHUB_OUTPUT

      # Ce step doit se lancer si le trigger se fait sur la branche develop
      - name: Build debug
        # conditionner ce step
        if: steps.build_type.outputs.MA_VAR == 'Debug'
        run: ./gradlew assembleDebug

      # Ce step doit se lancer si le trigger se fait sur la branche main
      - name: Build Release
        # conditionner ce step
        if: steps.build_type.outputs.MA_VAR == 'Release'
        run: ./gradlew assembleRelease