name: Build & upload APK to TestApp.io

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop

jobs:
  unit_test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Unit Tests
        run: ./gradlew test

  build:
    name: Build and upload to TestApp.io
    needs: unit_test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      # Déterminer le type de build + le chemin de l'APK
      - name: Determine build type
        id: build_type
        run: |
          echo "Branch: $GITHUB_REF_NAME"

          if [ "$GITHUB_REF_NAME" = "main" ]; then
            echo "MA_VAR=Release" >> "$GITHUB_OUTPUT"
            echo "APK_PATH=app/build/outputs/apk/release/app-release-unsigned.apk" >> "$GITHUB_OUTPUT"
          else
            # develop (ou autre) => Debug
            echo "MA_VAR=Debug" >> "$GITHUB_OUTPUT"
            echo "APK_PATH=app/build/outputs/apk/debug/app-debug.apk" >> "$GITHUB_OUTPUT"
          fi

      # Build Debug si branche = develop
      - name: Build Debug
        if: steps.build_type.outputs.MA_VAR == 'Debug'
        run: ./gradlew assembleDebug

      # Build Release si branche = main
      - name: Build Release
        if: steps.build_type.outputs.MA_VAR == 'Release'
        run: ./gradlew assembleRelease

      # Upload vers TestApp.io
      - name: Upload APK to TestApp.io
        uses: testappio/github-action@v5
        with:
          api_token: ${{ secrets.TOKENCICD }}   # ton secret TOKENCICD
          app_id: ${{ secrets.APP_ID }}         # ton secret APP_ID
          file: ${{ steps.build_type.outputs.APK_PATH }}
          release_notes: "CI build from ${{ github.ref_name }}"
          git_release_notes: true
          include_git_commit_id: true
          notify: true
